window.QUIZ_DATA = {
  slug: "arreglos-charat-length-01",
  titulo: "Arreglos, charAt() y length()",
  puntajeTotal: 10,
  preguntas: [
    { numero: 1, tipo: "radio", enunciado: `Observá:\n\nString palabra = "ALGORITMO";\nchar[] letras = {'J', 'A', 'V', 'A'};\n\nint posicion = letras.length - 2;\nchar resultado = palabra.charAt(posicion);\n\n¿Qué queda almacenado en resultado?`, opciones: [{ valor: "a", texto: "'O'" }, { valor: "b", texto: "'G'" }, { valor: "c", texto: "'L'" }, { valor: "d", texto: "'A'" }] },
    { numero: 2, tipo: "radio", enunciado: `Observá:\n\nString[] nombres = {"Ana", "Martín", "Sol", "Lucía"};\n\nint posicion = nombres[1].length() - nombres[2].length();\nSystem.out.println(nombres[posicion]);\n\n¿Qué se muestra en pantalla?`, opciones: [{ valor: "a", texto: "Martín" }, { valor: "b", texto: "Ana" }, { valor: "c", texto: "Sol" }, { valor: "d", texto: "Lucía" }] },
    { numero: 3, tipo: "radio", enunciado: `Observá:\n\nString texto = "PROGRAMAR";\nint[] posiciones = {0, 3, 5, 7};\n\nchar letra = texto.charAt(posiciones[2]);\nSystem.out.println(letra);\n\n¿Qué imprime?`, opciones: [{ valor: "a", texto: "R" }, { valor: "b", texto: "M" }, { valor: "c", texto: "A" }, { valor: "d", texto: "G" }] },
    { numero: 4, tipo: "radio", enunciado: `Analizá:\n\nString[] palabras = {"sol", "luna", "estrella"};\n\nint total = 0;\n\nfor (int i = 0; i < palabras.length; i++) {\n    total = total + palabras[i].length();\n}\n\nSystem.out.println(total);\n\n¿Cuál es la salida?`, opciones: [{ valor: "a", texto: "11" }, { valor: "b", texto: "15" }, { valor: "c", texto: "3" }, { valor: "d", texto: "12" }] },
    { numero: 5, tipo: "radio", enunciado: `Observá cuidadosamente:\n\nString palabra = "COMPUTADORA";\nint[] posiciones = {1, 4, 7};\n\nfor (int i = 0; i < posiciones.length; i++) {\n    System.out.print(palabra.charAt(posiciones[i]));\n}\n\n¿Qué se muestra?`, opciones: [{ valor: "a", texto: "OMD" }, { valor: "b", texto: "CUP" }, { valor: "c", texto: "OUD" }, { valor: "d", texto: "OPA" }] },
    { numero: 6, tipo: "radio", enunciado: `Se quiere mostrar el último carácter de cada palabra:\n\nString[] palabras = {"Java", "Sol", "Código"};\n\nfor (int i = 0; i < palabras.length; i++) {\n    System.out.print(palabras[i].charAt( ______ ));\n}\n\n¿Qué expresión debe colocarse en el espacio?`, opciones: [{ valor: "a", texto: "palabras.length - 1" }, { valor: "b", texto: "palabras[i].length()" }, { valor: "c", texto: "i - 1" }, { valor: "d", texto: "palabras[i].length() - 1" }] },
    { numero: 7, tipo: "radio", enunciado: `Observá:\n\nString[] datos = {"uno", "dos", "tres"};\n\nfor (int i = 0; i <= datos.length; i++) {\n    System.out.println(datos[i]);\n}\n\nEl programa mostrará correctamente las tres palabras y luego terminará.`, opciones: [{ valor: "v", texto: "Verdadero" }, { valor: "f", texto: "Falso" }] },
    { numero: 8, tipo: "radio", enunciado: `Observá:\n\nString palabra = "JAVA";\n\nfor (int i = 0; i < palabra.length(); i++) {\n    System.out.print(palabra.charAt(i));\n}\n\nEl programa recorre todas las posiciones válidas del String, desde 0 hasta 3, y muestra JAVA.`, opciones: [{ valor: "v", texto: "Verdadero" }, { valor: "f", texto: "Falso" }] },
    { numero: 9, tipo: "radio", enunciado: `Observá:\n\nString[] palabras = {"gato", "pez", "caballo"};\n\nint mayor = palabras[0].length();\n\nfor (int i = 1; i < palabras.length; i++) {\n    if (palabras[i].length() > mayor) {\n        mayor = palabras[i].length();\n    }\n}\n\nSystem.out.println(mayor);\n\nEl valor que finalmente se imprime es 7, porque el programa conserva el largo de la palabra más larga encontrada.`, opciones: [{ valor: "v", texto: "Verdadero" }, { valor: "f", texto: "Falso" }] },
    { numero: 10, tipo: "radio", enunciado: `Observá:\n\nString palabra = "MUNDO";\nint[] posiciones = {0, 2, 5};\n\nfor (int i = 0; i < posiciones.length; i++) {\n    System.out.print(palabra.charAt(posiciones[i]));\n}\n\nEl programa imprime MNO, porque el arreglo posiciones contiene tres posiciones.`, opciones: [{ valor: "v", texto: "Verdadero" }, { valor: "f", texto: "Falso" }] },
  ],
};
