window.QUIZ_DATA = {
  slug: "modelo-02",
  titulo: "POO: análisis y razonamiento",
  puntajeTotal: 10,
  preguntas: [
    { numero: 1, tipo: "radio", enunciado: "Observá: Producto p1 = new Producto(\"Mouse\", 850); Producto p2 = p1; Producto p3 = new Producto(\"Teclado\", 1200); p2.setPrecio(900); ¿Cuál afirmación es correcta?", opciones: [
      { valor: "a", texto: "A. Existen tres objetos Producto diferentes." }, { valor: "b", texto: "B. p1 y p2 hacen referencia al mismo objeto, cuyo precio ahora es 900." }, { valor: "c", texto: "C. p1 mantiene el precio 850 y p2 tiene precio 900." }, { valor: "d", texto: "D. p2 = p1 crea una copia completa del objeto almacenado en p1." }] },
    { numero: 2, tipo: "radio", enunciado: "Crear una clase Persona con nombre, documento y teléfono, para que Profesor, Estudiante y Funcionario hereden de ella, es razonable solamente porque evita repetir atributos, aunque conceptualmente no sean tipos de Persona.", opciones: [{ valor: "verdadero", texto: "Verdadero" }, { valor: "falso", texto: "Falso" }] },
    { numero: 3, tipo: "radio", enunciado: "En un sistema de ventas se propone Producto ← Venta porque una venta contiene productos. ¿Cuál es el mejor análisis?", opciones: [
      { valor: "a", texto: "A. Es correcto: cuando una clase utiliza objetos de otra conviene aplicar herencia." }, { valor: "b", texto: "B. Es incorrecto únicamente porque Producto debería heredar de Venta." }, { valor: "c", texto: "C. Es incorrecto: una Venta no es un Producto; se necesita una relación, no herencia." }, { valor: "d", texto: "D. Es correcto si Venta sobrescribe un método de Producto." }] },
    { numero: 4, tipo: "radio", enunciado: "Los equipos pueden participar en distintos torneos y existir aun sin participar en ninguno. ¿Qué relación representa mejor Torneo–Equipo?", opciones: [
      { valor: "a", texto: "A. Agregación o asociación que permita existencia independiente." }, { valor: "b", texto: "B. Composición, porque al finalizar el torneo se destruyen los equipos." }, { valor: "c", texto: "C. Herencia, porque cada equipo es un tipo de torneo." }, { valor: "d", texto: "D. Instanciación, porque un torneo crea equipos." }] },
    { numero: 5, tipo: "radio", enunciado: "Una Factura contiene varios DetalleFactura. Cada detalle solo registra producto, cantidad y precio de esa factura, y no tiene sentido independiente si se elimina la factura. Modelar Factura–DetalleFactura mediante composición es razonable.", opciones: [{ valor: "verdadero", texto: "Verdadero" }, { valor: "falso", texto: "Falso" }] },
    { numero: 6, tipo: "radio", enunciado: "Un comercio inicialmente vende Comic y luego incorpora Figura y Juego. Todos comparten código, nombre, precio y stock, pero tienen rasgos propios. ¿Cuál es la refactorización más adecuada?", opciones: [
      { valor: "a", texto: "A. Producto hereda de Comic porque Comic fue creado primero." }, { valor: "b", texto: "B. Crear Producto como clase general y Comic, Figura y Juego como especializaciones." }, { valor: "c", texto: "C. Hacer que Comic contenga un Producto solo para reutilizar atributos." }, { valor: "d", texto: "D. Una sola clase con todos los atributos posibles, dejando algunos en null." }] },
    { numero: 7, tipo: "radio", enunciado: "Cliente c = new Cliente(\"Lucía\"); Pedido p1 = new Pedido(c); Pedido p2 = new Pedido(c); ¿Qué se concluye correctamente?", opciones: [
      { valor: "a", texto: "A. Cada Pedido crea automáticamente una copia diferente de Cliente." }, { valor: "b", texto: "B. Al ser atributo, Cliente implica obligatoriamente composición." }, { valor: "c", texto: "C. p1 y p2 son el mismo pedido por usar el mismo cliente." }, { valor: "d", texto: "D. Hay dos Pedido diferentes relacionados con el mismo Cliente." }] },
    { numero: 8, tipo: "radio", enunciado: "En un modelo OO una Tienda tiene Cliente ── List<Venta>. Al diseñar la base de datos, necesariamente debe existir en Cliente una columna que contenga directamente una lista de ventas.", opciones: [{ valor: "verdadero", texto: "Verdadero" }, { valor: "falso", texto: "Falso" }] },
    { numero: 9, tipo: "radio", enunciado: "Los espacios físicos de una UTU comparten nombre, capacidad y ubicación. Laboratorio agrega computadoras, Gimnasio gradas y Salon proyector. ¿Qué diseño es mejor?", opciones: [
      { valor: "a", texto: "A. Una sola clase Espacio con todos los atributos, aunque muchos no correspondan." }, { valor: "b", texto: "B. Espacio como clase general, con Laboratorio, Gimnasio y Salon como especializaciones." }, { valor: "c", texto: "C. Laboratorio hereda de Gimnasio, que hereda de Salon." }, { valor: "d", texto: "D. Tres clases sin relación y con los atributos comunes repetidos." }] },
    { numero: 10, tipo: "radio", enunciado: "En una cantina, Cliente y Empleado son tipos de Persona; una Venta pertenece a Cliente y contiene DetalleVenta; cada detalle refiere a un Producto, que existe independientemente. ¿Cuál modelo es más coherente?", opciones: [
      { valor: "a", texto: "A. Cliente y Empleado heredan de Persona; Venta se relaciona con Cliente; Venta compone DetalleVenta; detalle se relaciona con Producto." }, { valor: "b", texto: "B. Persona hereda de Cliente y Empleado; Producto hereda de DetalleVenta; Venta compone Cliente." }, { valor: "c", texto: "C. Venta hereda de Cliente; DetalleVenta hereda de Producto; Empleado compone Persona." }, { valor: "d", texto: "D. Todas las clases se relacionan mediante composición." }] },
  ],
};
