window.QUIZ_DATA = {
  slug: "metodos-java-01",
  titulo: "Métodos en Java — Actividad 1",
  descripcion: "Práctica introductoria sobre declaración, parámetros, retorno y uso de métodos en Java.",
  puntajeTotal: 20,
  preguntas: [
    { numero: 1, tipo: "radio", enunciado: `¿Cuál es la declaración correcta de mostrarSaludo(), que solo muestra un mensaje y no recibe datos?\n\npublic static void mostrarSaludo() {\n    System.out.println("Bienvenidos a Programación I");\n}`, opciones: [{ valor: "a", texto: "public static void mostrarSaludo() { ... }" }, { valor: "b", texto: "public static int mostrarSaludo() { ... }" }, { valor: "c", texto: "public static mostrarSaludo(void) { ... }" }, { valor: "d", texto: "public static void mostrarSaludo(String mensaje) { ... }" }] },
    { numero: 2, tipo: "radio", enunciado: `El método mostrarSeparador() imprime una línea de guiones. No recibe datos ni entrega un resultado. ¿Qué tipo debe aparecer antes de su nombre?\n\npublic static _____ mostrarSeparador() {\n    System.out.println("--------------------");\n}`, opciones: [{ valor: "a", texto: "void" }, { valor: "b", texto: "int" }, { valor: "c", texto: "String" }, { valor: "d", texto: "return" }] },
    { numero: 3, tipo: "radio", enunciado: `¿Qué llamada ejecuta correctamente un método sin parámetros llamado mostrarMenu()?\n\npublic static void mostrarMenu() {\n    System.out.println("1. Sumar");\n}`, opciones: [{ valor: "a", texto: "mostrarMenu();" }, { valor: "b", texto: "mostrarMenu;" }, { valor: "c", texto: "mostrarMenu(void);" }, { valor: "d", texto: "void mostrarMenu();" }] },
    { numero: 4, tipo: "radio", enunciado: `mostrarFirma() debe mostrar el nombre y versión de un programa, sin recibir ni devolver datos. ¿Cuál línea completa correctamente el método?\n\npublic static void mostrarFirma() {\n    _____\n    System.out.println("Versión 1.0");\n}`, opciones: [{ valor: "a", texto: "System.out.println(\"Calculadora PM\");" }, { valor: "b", texto: "return \"Calculadora PM\";" }, { valor: "c", texto: "int Calculadora PM;" }, { valor: "d", texto: "mostrarFirma = \"Calculadora PM\";" }] },
    { numero: 5, tipo: "radio", enunciado: `Observá la declaración y la llamada:\n\npublic static void saludarPersona(String nombre) {\n    System.out.println("Hola, " + nombre);\n}\nsaludarPersona("Ana");\n\n¿Qué es nombre?`, opciones: [{ valor: "a", texto: "Un parámetro: aparece en la declaración del método." }, { valor: "b", texto: "Un argumento: es el valor enviado al llamar." }, { valor: "c", texto: "El retorno del método." }, { valor: "d", texto: "Una variable obligatoriamente global." }] },
    { numero: 6, tipo: "radio", enunciado: `mostrarDoble recibe un entero y debe mostrar su doble, sin devolverlo. ¿Qué línea va dentro del método?\n\npublic static void mostrarDoble(int numero) {\n    _____\n}`, opciones: [{ valor: "a", texto: "System.out.println(numero * 2);" }, { valor: "b", texto: "return numero * 2;" }, { valor: "c", texto: "int = numero * 2;" }, { valor: "d", texto: "mostrarDoble(numero * 2);" }] },
    { numero: 7, tipo: "radio", enunciado: `¿Cuál es la firma correcta para mostrar el nombre y el precio de un producto?`, opciones: [{ valor: "a", texto: "public static void mostrarProducto(String nombre, double precio)" }, { valor: "b", texto: "public static void mostrarProducto(String nombre)" }, { valor: "c", texto: "public static double mostrarProducto(String precio, double nombre)" }, { valor: "d", texto: "public static void mostrarProducto(double nombre, String precio)" }] },
    { numero: 8, tipo: "radio", enunciado: `El método es:\n\npublic static void mostrarEdad(String nombre, int edad) {\n    System.out.println(nombre + ": " + edad);\n}\n\n¿Cuál llamada es correcta?`, opciones: [{ valor: "a", texto: "mostrarEdad(\"Lucía\", 17);" }, { valor: "b", texto: "mostrarEdad(17, \"Lucía\");" }, { valor: "c", texto: "mostrarEdad(\"Lucía\");" }, { valor: "d", texto: "int mostrarEdad(\"Lucía\", 17);" }] },
    { numero: 9, tipo: "radio", enunciado: `sumar debe entregar la suma para poder usarla después. ¿Cuál línea es correcta?\n\npublic static int sumar(int a, int b) {\n    _____\n}`, opciones: [{ valor: "a", texto: "return a + b;" }, { valor: "b", texto: "System.out.println(a + b);" }, { valor: "c", texto: "void a + b;" }, { valor: "d", texto: "return;" }] },
    { numero: 10, tipo: "radio", enunciado: `calcularDoble devuelve un int. ¿Cuál uso permite guardar su resultado?\n\npublic static int calcularDoble(int numero) {\n    return numero * 2;\n}`, opciones: [{ valor: "a", texto: "int resultado = calcularDoble(8);" }, { valor: "b", texto: "calcularDoble = resultado(8);" }, { valor: "c", texto: "void resultado = calcularDoble(8);" }, { valor: "d", texto: "int resultado = mostrarDoble(8);" }] },
    { numero: 11, tipo: "radio", enunciado: `¿Qué debe devolver calcularPrecioConIva para agregar 22 % a un precio double?\n\npublic static double calcularPrecioConIva(double precio) {\n    _____\n}`, opciones: [{ valor: "a", texto: "return precio * 1.22;" }, { valor: "b", texto: "return precio + 22;" }, { valor: "c", texto: "System.out.println(precio * 1.22);" }, { valor: "d", texto: "return int precio * 1.22;" }] },
    { numero: 12, tipo: "radio", enunciado: `¿Cuál retorno calcula correctamente el promedio de tres notas?\n\npublic static double calcularPromedio(double nota1, double nota2, double nota3) {\n    _____\n}`, opciones: [{ valor: "a", texto: "return (nota1 + nota2 + nota3) / 3;" }, { valor: "b", texto: "return nota1 + nota2 + nota3 / 3;" }, { valor: "c", texto: "System.out.println((nota1 + nota2 + nota3) / 3);" }, { valor: "d", texto: "return (nota1 + nota2 + nota3) / \"3\";" }] },
    { numero: 13, tipo: "radio", enunciado: `¿Qué retorno expresa correctamente que una persona es mayor de edad desde los 18 años?\n\npublic static boolean esMayorDeEdad(int edad) {\n    _____\n}`, opciones: [{ valor: "a", texto: "return edad >= 18;" }, { valor: "b", texto: "return edad = 18;" }, { valor: "c", texto: "return edad > 18;" }, { valor: "d", texto: "System.out.println(edad >= 18);" }] },
    { numero: 14, tipo: "radio", enunciado: `¿Cuál método devuelve true cuando numero es par?`, opciones: [{ valor: "a", texto: "return numero % 2 == 0;" }, { valor: "b", texto: "return numero / 2;" }, { valor: "c", texto: "return numero % 2 = 0;" }, { valor: "d", texto: "return numero % 2 == 1;" }] },
    { numero: 15, tipo: "radio", enunciado: `Según el criterio del curso, una nota de 5 o más aprueba. ¿Qué debe devolver estaAprobado?\n\npublic static boolean estaAprobado(int nota) {\n    _____\n}`, opciones: [{ valor: "a", texto: "return nota >= 5;" }, { valor: "b", texto: "return nota > 5;" }, { valor: "c", texto: "return nota = 5;" }, { valor: "d", texto: "return \"aprobado\";" }] },
    { numero: 16, tipo: "radio", enunciado: `Para comparar el contenido de una clave con \"java123\", ¿cuál es la línea correcta?\n\npublic static boolean esContrasenaCorrecta(String clave) {\n    _____\n}`, opciones: [{ valor: "a", texto: "return clave.equals(\"java123\");" }, { valor: "b", texto: "return clave == \"java123\";" }, { valor: "c", texto: "return clave = \"java123\";" }, { valor: "d", texto: "return equals(clave, \"java123\");" }] },
    { numero: 17, tipo: "radio", enunciado: `mostrarVuelto(pago, costo) imprime el vuelto. calcularVuelto(pago, costo) lo devuelve. Si después se quiere guardar, comparar o usar ese valor en otro cálculo, ¿cuál conviene usar?`, opciones: [{ valor: "a", texto: "calcularVuelto, porque return entrega un valor reutilizable." }, { valor: "b", texto: "mostrarVuelto, porque println guarda automáticamente el resultado." }, { valor: "c", texto: "Cualquiera: void y return producen lo mismo." }, { valor: "d", texto: "Ninguno: los métodos no pueden recibir double." }] },
    { numero: 18, tipo: "radio", enunciado: `Una calculadora tiene sumar, restar, multiplicar y dividir. Todos reciben dos double y devuelven el resultado. ¿Cuál firma corresponde a dividir?`, opciones: [{ valor: "a", texto: "public static double dividir(double a, double b)" }, { valor: "b", texto: "public static void dividir(double a, double b)" }, { valor: "c", texto: "public static boolean dividir(double a, double b)" }, { valor: "d", texto: "public static double dividir(double a)" }] },
    { numero: 19, tipo: "radio", enunciado: `Una entrada cuesta $250. Observá esta secuencia:\n\ndouble total = calcularTotalEntradas(3);\nmostrarResumenCompra(3, total);\n\n¿Qué representa total en la segunda llamada?`, opciones: [{ valor: "a", texto: "El resultado devuelto por calcularTotalEntradas, usado como argumento." }, { valor: "b", texto: "Un parámetro declarado dentro de mostrarResumenCompra." }, { valor: "c", texto: "El nombre de un método void." }, { valor: "d", texto: "Un String con el nombre del producto." }] },
    { numero: 20, tipo: "radio", enunciado: `En el mini sistema de notas se calcula un promedio, se decide si aprueba y se muestra el resultado. ¿Cuál es la secuencia correcta?`, opciones: [{ valor: "a", texto: "double promedio = calcularPromedio(n1, n2, n3); boolean aprobado = estaAprobado(promedio); mostrarResultado(nombre, promedio, aprobado);" }, { valor: "b", texto: "mostrarResultado(nombre); calcularPromedio(n1, n2, n3);" }, { valor: "c", texto: "boolean promedio = estaAprobado(n1); mostrarResultado(nombre, promedio);" }, { valor: "d", texto: "int aprobado = mostrarResultado(nombre, n1, true);" }] },
  ],
};

// Se varía el orden visible para que la posición no sugiera una respuesta.
const ordenOpcionesMetodos01 = {
  1: [2, 0, 3, 1], 2: [1, 3, 0, 2], 3: [2, 1, 3, 0], 4: [3, 0, 2, 1],
  5: [1, 3, 0, 2], 6: [2, 0, 3, 1], 7: [3, 1, 0, 2], 8: [1, 2, 0, 3],
  9: [1, 3, 0, 2], 10: [3, 0, 2, 1], 11: [2, 0, 3, 1], 12: [1, 3, 0, 2],
  13: [2, 0, 3, 1], 14: [3, 1, 0, 2], 15: [1, 3, 0, 2], 16: [2, 0, 3, 1],
  17: [1, 3, 0, 2], 18: [2, 0, 3, 1], 19: [3, 1, 0, 2], 20: [1, 3, 0, 2],
};

window.QUIZ_DATA.preguntas.forEach((pregunta) => {
  pregunta.opciones = ordenOpcionesMetodos01[pregunta.numero].map(
    (indice) => pregunta.opciones[indice],
  );
});
