window.QUIZ_DATA = {
  slug: "arreglos-numericos-02",
  titulo: "Recorrido de arreglos numéricos",
  puntajeTotal: 10,
  preguntas: [
    { numero: 1, tipo: "radio", enunciado: `Observá el siguiente código:\n\nint[] numeros = {4, 7, 2, 9, 5};\nint suma = 0;\n\nfor (int i = 1; i < numeros.length; i++) {\n    suma = suma + numeros[i];\n}\n\nSystem.out.println(suma);\n\n¿Qué se muestra en pantalla?`, opciones: [{ valor: "a", texto: "27" }, { valor: "b", texto: "18" }, { valor: "c", texto: "23" }, { valor: "d", texto: "5" }] },
    { numero: 2, tipo: "radio", enunciado: `Analizá:\n\nint[] valores = {3, 8, 4, 10, 6};\nint contador = 0;\n\nfor (int i = 0; i < valores.length; i++) {\n    if (valores[i] > 5) {\n        contador++;\n    }\n}\n\nSystem.out.println(contador);\n\n¿Qué valor se imprime?`, opciones: [{ valor: "a", texto: "3" }, { valor: "b", texto: "28" }, { valor: "c", texto: "2" }, { valor: "d", texto: "5" }] },
    { numero: 3, tipo: "radio", enunciado: `Observá con atención:\n\nint[] numeros = {5, 2, 8, 3, 6};\n\nfor (int i = 0; i < numeros.length; i++) {\n    if (numeros[i] % 2 == 0) {\n        numeros[i] = numeros[i] + 1;\n    }\n}\n\nSystem.out.println(numeros[2]);\n\n¿Qué se imprime?`, opciones: [{ valor: "a", texto: "6" }, { valor: "b", texto: "3" }, { valor: "c", texto: "8" }, { valor: "d", texto: "9" }] },
    { numero: 4, tipo: "radio", enunciado: `Analizá:\n\nint[] datos = {12, 7, 15, 4, 10};\nint mayor = datos[0];\n\nfor (int i = 1; i < datos.length; i++) {\n    if (datos[i] > mayor) {\n        mayor = datos[i];\n    }\n}\n\nSystem.out.println(mayor);\n\n¿Qué imprime el programa?`, opciones: [{ valor: "a", texto: "12" }, { valor: "b", texto: "15" }, { valor: "c", texto: "10" }, { valor: "d", texto: "4" }] },
    { numero: 5, tipo: "radio", enunciado: `Observá:\n\nint[] numeros = {2, 4, 6, 8, 10, 12};\nint suma = 0;\n\nfor (int i = 0; i < numeros.length; i = i + 2) {\n    suma = suma + numeros[i];\n}\n\nSystem.out.println(suma);\n\n¿Qué resultado se muestra?`, opciones: [{ valor: "a", texto: "18" }, { valor: "b", texto: "42" }, { valor: "c", texto: "24" }, { valor: "d", texto: "12" }] },
    { numero: 6, tipo: "radio", enunciado: `Analizá cuidadosamente:\n\nint[] numeros = {7, 3, 9, 2, 6};\nint resultado = 0;\n\nfor (int i = 0; i < numeros.length; i++) {\n    if (i % 2 == 0) {\n        resultado = resultado + numeros[i];\n    }\n}\n\nSystem.out.println(resultado);\n\n¿Qué imprime?`, opciones: [{ valor: "a", texto: "12" }, { valor: "b", texto: "27" }, { valor: "c", texto: "22" }, { valor: "d", texto: "15" }] },
    { numero: 7, tipo: "radio", enunciado: `Observá:\n\nint[] numeros = {5, 8, 2, 7};\nint suma = 0;\n\nfor (int i = 0; i < numeros.length - 1; i++) {\n    suma = suma + numeros[i];\n}\n\nAl terminar el recorrido, suma vale 22 porque se sumaron todos los elementos del arreglo.`, opciones: [{ valor: "v", texto: "Verdadero" }, { valor: "f", texto: "Falso" }] },
    { numero: 8, tipo: "radio", enunciado: `Observá:\n\nint[] valores = {4, 9, 3, 12, 5};\nint contador = 0;\n\nfor (int i = 0; i < valores.length; i++) {\n    if (valores[i] < 6) {\n        contador++;\n    }\n}\n\nAl terminar el for, contador vale 3.`, opciones: [{ valor: "v", texto: "Verdadero" }, { valor: "f", texto: "Falso" }] },
    { numero: 9, tipo: "radio", enunciado: `Analizá:\n\nint[] numeros = {10, 20, 30, 40};\n\nfor (int i = 0; i < numeros.length; i++) {\n    numeros[i] = numeros[i] / 10;\n}\n\nDespués del recorrido, el arreglo contiene {1, 2, 3, 4}.`, opciones: [{ valor: "v", texto: "Verdadero" }, { valor: "f", texto: "Falso" }] },
    { numero: 10, tipo: "radio", enunciado: `Observá:\n\nint[] numeros = {6, 3, 8, 1, 5};\nint menor = numeros[0];\n\nfor (int i = 1; i < numeros.length; i++) {\n    if (numeros[i] < menor) {\n        menor = numeros[i];\n    }\n}\n\nAl terminar el recorrido, menor vale 3, porque es el primer número menor que 6 que encuentra el programa.`, opciones: [{ valor: "v", texto: "Verdadero" }, { valor: "f", texto: "Falso" }] },
  ],
};
