window.QUIZ_DATA = {
  slug: "iterativas-java-03",
  titulo: "Repetición y decisiones en Java - Actividad 1",
  puntajeTotal: 20,
  preguntas: [
    { numero: 1, tipo: "radio", enunciado: `Observá el código:\n\nint numero = 1;\nwhile (numero <= 4) {\n    System.out.println(numero);\n    numero++;\n}\n\n¿Cuál es la salida?`, opciones: [{ valor: "a", texto: "1 2 3 4" }, { valor: "b", texto: "0 1 2 3 4" }, { valor: "c", texto: "1 2 3" }, { valor: "d", texto: "El programa se repite sin terminar" }] },
    { numero: 2, tipo: "radio", enunciado: "En un while con contador, si olvidamos aumentar o disminuir el contador dentro del bloque, el ciclo puede no terminar nunca.", opciones: [{ valor: "a", texto: "Verdadero" }, { valor: "b", texto: "Falso" }] },
    { numero: 3, tipo: "radio", enunciado: `¿Qué opción completa el código para que muestre los números 1, 2, 3, 4 y 5?\n\nint i = 1;\nwhile (i <= 5) {\n    System.out.println(i);\n    __________\n}`, opciones: [{ valor: "a", texto: "i++;" }, { valor: "b", texto: "i = 1;" }, { valor: "c", texto: "i--;" }, { valor: "d", texto: "System.out.println(i);" }] },
    { numero: 4, tipo: "radio", enunciado: `¿Cuál de estos for produce exactamente la misma salida que este código?\n\nint vuelta = 1;\nwhile (vuelta <= 3) {\n    System.out.println("Vuelta " + vuelta);\n    vuelta++;\n}`, opciones: [{ valor: "a", texto: "for (int vuelta = 1; vuelta <= 3; vuelta++) { System.out.println(\"Vuelta \" + vuelta); }" }, { valor: "b", texto: "for (int vuelta = 0; vuelta <= 3; vuelta++) { System.out.println(\"Vuelta \" + vuelta); }" }, { valor: "c", texto: "for (int vuelta = 1; vuelta < 3; vuelta++) { System.out.println(\"Vuelta \" + vuelta); }" }, { valor: "d", texto: "for (int vuelta = 1; vuelta <= 3; vuelta--) { System.out.println(\"Vuelta \" + vuelta); }" }] },
    { numero: 5, tipo: "radio", enunciado: "Si sabemos que una acción debe repetirse exactamente 8 veces, un for suele ser una opción clara porque reúne inicio, condición y actualización en una sola línea.", opciones: [{ valor: "a", texto: "Verdadero" }, { valor: "b", texto: "Falso" }] },
    { numero: 6, tipo: "radio", enunciado: `Leé el programa:\n\nint dato;\ndo {\n    System.out.print("Ingrese un número (0 termina): ");\n    dato = scanner.nextInt();\n} while (dato != 0);\n\n¿Qué clase de repetición se usa?`, opciones: [{ valor: "a", texto: "Con centinela" }, { valor: "b", texto: "Con contador" }, { valor: "c", texto: "Con bandera" }, { valor: "d", texto: "Infinita" }] },
    { numero: 7, tipo: "radio", enunciado: "En el programa anterior, una persona ingresa: 7, -2, 0. ¿Cuántas veces aparece el mensaje “Ingrese un número (0 termina):”?", opciones: [{ valor: "a", texto: "3" }, { valor: "b", texto: "2" }, { valor: "c", texto: "4" }, { valor: "d", texto: "0" }] },
    { numero: 8, tipo: "radio", enunciado: "Un do...while ejecuta primero las instrucciones del bloque y recién después comprueba la condición.", opciones: [{ valor: "a", texto: "Verdadero" }, { valor: "b", texto: "Falso" }] },
    { numero: 9, tipo: "radio", enunciado: `Completá la condición para que este menú se repita hasta que el usuario elija la opción 0:\n\nint opcion;\ndo {\n    System.out.println("1. Consultar");\n    System.out.println("0. Salir");\n    opcion = scanner.nextInt();\n} while ( __________ );`, opciones: [{ valor: "a", texto: "opcion != 0" }, { valor: "b", texto: "opcion == 0" }, { valor: "c", texto: "opcion < 0" }, { valor: "d", texto: "opcion = 0" }] },
    { numero: 10, tipo: "radio", enunciado: `Leé el siguiente fragmento de un menú:\n\nswitch (opcion) {\n    case 1:\n        System.out.println("Agregar producto");\n        break;\n    case 2:\n        System.out.println("Ver total");\n        break;\n    case 0:\n        System.out.println("Hasta luego");\n        break;\n    default:\n        System.out.println("Opción inválida");\n}\n\nSi opcion vale 5, ¿qué se imprime?`, opciones: [{ valor: "a", texto: "Opción inválida" }, { valor: "b", texto: "Agregar producto" }, { valor: "c", texto: "Ver total" }, { valor: "d", texto: "Hasta luego" }] },
    { numero: 11, tipo: "radio", enunciado: "En un switch, default se ejecuta obligatoriamente después de cada case.", opciones: [{ valor: "a", texto: "Verdadero" }, { valor: "b", texto: "Falso" }] },
    { numero: 12, tipo: "radio", enunciado: `¿Para qué sirve break en este switch?\n\ncase 1:\n    System.out.println("Cargar datos");\n    break;`, opciones: [{ valor: "a", texto: "Para evitar que continúe ejecutando el case siguiente." }, { valor: "b", texto: "Para repetir el menú." }, { valor: "c", texto: "Para volver a pedir el número." }, { valor: "d", texto: "Para cerrar Scanner." }] },
    { numero: 13, tipo: "radio", enunciado: `Un sistema permite hasta 3 intentos para ingresar un PIN. Debe detenerse antes si el PIN es correcto. ¿Qué condición representa mejor esa idea?\n\nint intentos = 0;\nint pin;\n// se pide pin dentro del ciclo\nwhile ( _______________________ ) { ... }`, opciones: [{ valor: "a", texto: "intentos < 3 && pin != 1234" }, { valor: "b", texto: "intentos < 3 || pin != 1234" }, { valor: "c", texto: "intentos == 3 && pin == 1234" }, { valor: "d", texto: "intentos < 3 && pin == 1234" }] },
    { numero: 14, tipo: "radio", enunciado: "En una condición combinada con &&, si una de las dos condiciones es falsa, todo el resultado es falso.", opciones: [{ valor: "a", texto: "Verdadero" }, { valor: "b", texto: "Falso" }] },
    { numero: 15, tipo: "radio", enunciado: "En el control de PIN, la persona acierta en el segundo intento. ¿Cuántas veces se repite el bloque si se usa correctamente la condición while (intentos < 3 && pin != 1234)?", opciones: [{ valor: "a", texto: "2" }, { valor: "b", texto: "1" }, { valor: "c", texto: "3" }, { valor: "d", texto: "0" }] },
    { numero: 16, tipo: "radio", enunciado: "Se quiere buscar el número 8 entre valores que se van ingresando. El ingreso termina cuando aparece el 8 o cuando se ingresa 0. ¿Qué variable conviene usar para recordar si fue encontrado?", opciones: [{ valor: "a", texto: "boolean encontrado = false;" }, { valor: "b", texto: "int encontrado = 8;" }, { valor: "c", texto: "double encontrado = 0;" }, { valor: "d", texto: "char encontrado = 'S';" }] },
    { numero: 17, tipo: "radio", enunciado: `Observá este código:\n\nboolean encontrado = false;\nint numero = 0;\nwhile (!encontrado && numero != 0) {\n    // pedir un número\n}\n\n¿Qué significa !encontrado?`, opciones: [{ valor: "a", texto: "“No encontrado”: encontrado vale false." }, { valor: "b", texto: "“Encontrado”: encontrado vale true." }, { valor: "c", texto: "“Número negativo”." }, { valor: "d", texto: "“Distinto de cero”." }] },
    { numero: 18, tipo: "radio", enunciado: `Dentro de una búsqueda, después de pedir un número, se escribe:\n\nif (numero == 8) {\n    encontrado = true;\n}\n\n¿Por qué esto permite que el while (!encontrado ...) termine?`, opciones: [{ valor: "a", texto: "Porque !encontrado pasa a ser falso." }, { valor: "b", texto: "Porque numero se vuelve 0 automáticamente." }, { valor: "c", texto: "Porque el if repite el ciclo." }, { valor: "d", texto: "Porque Scanner se cierra." }] },
    { numero: 19, tipo: "radio", enunciado: "En un ciclo de búsqueda con bandera, la variable bandera debe cambiar en algún momento; de lo contrario, la condición puede quedar siempre igual.", opciones: [{ valor: "a", texto: "Verdadero" }, { valor: "b", texto: "Falso" }] },
    { numero: 20, tipo: "radio", enunciado: `Leé el código:\n\nint i = 1;\nwhile (i <= 3) {\n    System.out.println(i);\n}\n\n¿Qué problema presenta?`, opciones: [{ valor: "a", texto: "Ciclo infinito: i nunca cambia." }, { valor: "b", texto: "Solo imprime 1 una vez." }, { valor: "c", texto: "Error porque while no puede usar enteros." }, { valor: "d", texto: "Imprime 1, 2 y 3 correctamente." }] },
  ],
};

// La versión para 1MG presenta las mismas consignas con un orden de opciones distinto.
const ordenOpcionesActividad03 = {
  1: [1, 2, 0, 3], 2: [1, 0], 3: [1, 2, 3, 0], 4: [1, 0, 2, 3],
  5: [0, 1], 6: [0, 1, 2, 3], 7: [1, 2, 0, 3], 8: [1, 0],
  9: [1, 2, 3, 0], 10: [1, 2, 0, 3], 11: [1, 0], 12: [1, 2, 3, 0],
  13: [1, 0, 2, 3], 14: [0, 1], 15: [0, 1, 2, 3], 16: [1, 2, 0, 3],
  17: [1, 2, 3, 0], 18: [1, 2, 0, 3], 19: [1, 0], 20: [1, 2, 3, 0],
};

window.QUIZ_DATA.preguntas.forEach((pregunta) => {
  const orden = ordenOpcionesActividad03[pregunta.numero];
  pregunta.opciones = orden.map((indice) => pregunta.opciones[indice]);
});
